# Generated by Django 3.1 on 2020-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10)),
                ('userId', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
