# Generated by Django 3.1 on 2020-08-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200813_0205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userinfo',
        ),
    ]
