# Generated by Django 3.1 on 2020-08-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20200815_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userPassword',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userIntro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userSex',
            field=models.CharField(blank=True, choices=[('XY', '여자'), ('XX', '남자')], max_length=2, null=True),
        ),
    ]
